<template>
  <page-layout title='ABS Sensor' heading-bg='customer-v2/static-pages/allpics/abs-sensor1.jpg'>
    <div class="container">
      <div class="row">
        <section class="col-12 col-lg-9 ma-page-main-side margin-bottom-20" style="padding-top: 40px;">
          <div class="row">
            <div class="col-12">
              <p class="text-teal text-18 justify">Ensuring your ABS sensors are in working order is essential – not
                just for an MOT, but for your overall safety too. ABS sensors are incredibly sensitive, individually
                monitoring the acceleration and deceleration of each wheel through an electromagnetic field generated by
                the wheel’s rotation. Fluctuations in this field are registered and sent as signals to the ABS
                controller unit, which instantly applies precise amounts of braking force to each wheel in order to
                boost performance and efficiency, as well as safety. Due to their proximity to the wheels and the
                ground, ABS sensors are exposed to constant heat, dirt and moisture, as well as vibrations and the
                occasional jolt; which can lead to malfunctions. Without reliable sensors, your ABS system can’t always
                keep you, your car and those around you safe, so taking the time to make sure your ABS sensors are of
                the highest quality is a must.</p>
            </div>
          </div>
          <v-expansion-panels popout>
            <v-expansion-panel  class="icon">
              <v-expansion-panel-header class="card-header">
                Importance of ABS sensors
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">The increasing complexity of the traffic situation on our roads is
                  placing high demands on car drivers. Driver assistance systems relieve the burden on the driver and
                  optimise road safety. As a result, state-of-the-art driving assistance systems are now included as
                  standard on virtually all new European vehicles. This also means that workshops are being faced with
                  new challenges. Nowadays, the vehicle electronics play a key role in all comfort and safety equipment.
                  Optimal interaction between complex electronic systems ensures that the vehicle operates without
                  problems, and this, in turn, increases road safety. Intelligent communication of data between
                  electronic vehicle systems is supported by sensors. When it comes to driving safety, speed sensors
                  play a particularly important role, and this is reflected by their varied use in a number of
                  different.</p>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                ABS Sensor vehicle systems
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">They are used by the control units in driving assistance systems
                  such as ABS, TCS, ESP, or ACC in order to detect the wheel speed. The wheel speed information is also
                  provided to other systems (engine, transmission, navigation, and chassis control systems) via data
                  lines by the ABS control unit. As a result of their varied use, speed sensors contribute directly to
                  the driving dynamics, driving safety, driving comfort, lower fuel consumption, and lower emissions.
                  Wheel speed sensors are often also called ABS sensors as they were used in vehicles for the first time
                  when ABS was introduced. Wheel speed sensors can be designed as active or passive sensors, depending
                  on how they operate. A clear and precise way of distinguishing or categorising them has not been
                  defined.</p>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                ABS Sensor Repair
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">ABS (or anti-lock braking system) is what keeps your wheels gripped
                  to the road when braking sharply, and prevents them from locking up to keep you in full control. The
                  hydraulic unit in the ABS system works by equalising the pressure on each individual brake or
                  adjusting it to stop the car from skidding or veering. Along with the ABS sensor, the hydraulic unit
                  is an important component in terms of your car’s safety, and we advise giving it the same TLC as the
                  rest of your vehicle.</p>

              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                What are the symptoms of a bad ABS sensor?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">

                <p class="text-teal text-18 justify">Symptoms of a Bad or Failing ABS Speed Sensor</p>
                <ul>
                  <li class="text-teal text-18 justify">The ABS Light.</li>
                  <li class="text-teal text-18 justify">Brakes take longer to stop car.</li>
                  <li class="text-teal text-18 justify">Less stability under icy or wet driving conditions.</li>
                  <li class="text-teal text-18 justify">The most obvious sign of a problem with the ABS system is that
                    the ABS Light will come on.</li>
                </ul>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                What causes ABS light to come on and stay on?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">An ABS light (anti-lock braking system) that is stuck on doesn't
                  necessarily mean you need an ABS brake repair. The light staying on can be caused by something as
                  simple as the emergency brake or more complicated things like a loss of brake fluid and pressure or
                  bad hydraulic valves.</p>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel  class="icon">
              <v-expansion-panel-header class="card-header">
                What happens if ABS light comes on?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">Your vehicle may not handle stopping on slippery surfaces like it
                  is designed to under heavy braking. If both your ABS Light and brake system light come on, this is an
                  emergency and you need to stop driving right away. Have your entire brake system inspected by a
                  certified mechanic, such as one from your Mechanic.</p>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                What can a faulty ABS sensor cause?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">There are other problems that will also cause this light to
                  illuminate including a faulty ABS pump, worn out brake pads, low brake fluid levels, issues with brake
                  pressure, or air trapped in the brake lines.</p>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                Why did my ABS light come on?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">If it finds it's lacking data, or a hydraulic pump or valve isn't
                  responding, it illuminates the ABS warning light on the dash. ABS rely on a properly operating
                  conventional brake system. If the ABS packs up, you should still have normal, unassisted braking, so
                  it's not safe to continue your journey.</p>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                What is ABS failure?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">Symptoms of a Bad or Failing ABS Control Module. The ABS system is
                  designed to help prevent wheels from locking during heavy braking situations, preventing the vehicle
                  from skidding or hydroplaning. The ABS system is made up of the ABS module, and ABS sensors at each
                  wheel.</p>

              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                ABS repairs Free Collection and Delivery
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">Sometimes, the worst part of getting your car fixed is having to
                  bring it to the garage. We are therefore happy to offer our customers a free collection and delivery
                  service If you prearrange a collection, we will pick your car up from your home or place of work and
                  drive it to our premises, carry out all the necessary work (having consulted you) and deliver it back
                  to you at the end of the day. </p>
                <p class="text-teal text-18 justify">We are able to tow, jump start or repair your vehicle if you are
                  experiencing problems or broken down for a small fee. If we can't sadly start your vehicle, we can
                  contact a local recovery firm to collect your vehicle for a very competitive price.</p>
                <ul class="list mt-2 mb-2">
                  <li>Don't want to waste your day off? </li>
                  <li>You don't have the time to take your car in for a service or repairs? </li>
                  <li>Have you got problems with getting to and from the garage? </li>
                </ul>
                <p class="text-teal text-18 justify">Here at Many Autos, we believe that we offer a valuable product
                  with our Free Collection and Delivery Service, we can collect either from your place of work or from
                  your home address. If you are unsure about whether the address you are considering having your vehicle
                  collected from is not within our range, then please do contact us.<br></p>
                <p class="text-teal text-18 justify">Many Autos operate a fleet of pool cars with a dedicated driver, so
                  wherever we are collecting from, we need to be able to leave one of our pool vehicles either in your
                  work car park / parking space, or if in a residential area, we would need to be able to leave our car
                  either at your house or on the road with a permit if required. We would be grateful if you could bear
                  this in mind when booking to use our free Collection and delivery service</p>

              </v-expansion-panel-content>
            </v-expansion-panel>
          </v-expansion-panels>

        </section>

      </div>
    </div>
  </page-layout>
</template>

<script>
import PageLayout from '@/layouts/page-layout';

const URL = process.env.APP_URL;

export default {
  components: {
    PageLayout
  },

  head: {
    title: 'ABS Sensor, ABS Ring ',

    meta: [
      {
        hid: 'description', name: 'description', 
        content: 'We repair ABS Sensor for all makes and models At Many Autos You will Find a Best Car Mechanic of UK to Repair or Replace your car’s ABS Sensor, ABS Ring and ABS hydraulic unit book your car Service online now.'
      },
      {
        name: 'keywords',
        content: 'abs sensor, ABS Sensor, ABS Ring and ABS hydraulic unit, Many Autos, Best Car Mechanic'
      },
      {
        hid: 'og:title',
        property: "og:title", 
        content: "ABS Sensor, ABS Ring"
      },
      {
        hid: 'og:type',
        property: "og:type", 
        content: "website"
      },
      {
        hid: 'og:url',
        property: "og:url", 
        content: URL
      },
      {
        hid: 'og:image',
        property: "og:image", 
        content: "logo-default.png"
      },
      {
        hid: 'og:site_name',
        property: "og:site_name", 
        content: "ManyAutos LTD"
      },
      {
        hid: 'og:description',  property: 'og:description', 
        content: "We repair ABS Sensor for all makes and models At Many Autos You will Find a Best Car Mechanic of UK to Repair or Replace your car’s ABS Sensor, ABS Ring and ABS hydraulic unit book your car Service online now."
      },
      {
        name: "twitter:card", 
        content: "summary"
      },
      {
        name: "twitter:title", 
        content: "ABS Sensor, ABS Ring"
      },
      {
        name: "twitter:description", 
        content: "We repair ABS Sensor for all makes and models At Many Autos You will Find a Best Car Mechanic of UK to Repair or Replace your car’s ABS Sensor, ABS Ring and ABS hydraulic unit book your car Service online now."
      },
      {
        name: "twitter:image", 
        content: "logo-default.png"
      },
      {
        itemprop: "image", 
        content: "logo-default.png"
      },
      {
        hid: 'og:type',
        property: "og:type", 
        content: "business.business"
      },
    ]
  }
}
</script>

<style lang="scss" scoped>
.card-header{
    background: whitesmoke;
    border: 1px solid #ececec;
    color: #1ea5c7;
    padding: 18px;
    font-weight: 400;
    font-size: 16px;
    line-height: normal;
}
.card-header-body{
    background-color: #fff;
    padding-top: 16px;
}
</style>