<template>
  <page-layout title='EGR' heading-bg='customer-v2/static-pages/allpics/egr1.jpg'>
    <div class="container">
      <div class="row">
        <section class="col-12 col-lg-9 ma-page-main-side margin-bottom-20" style="padding-top: 40px;">
          <div class="row">
            <div class="col-12">
              <p class="text-teal text-18 justify">Exhaust Gas Recirculation is a system designed primarily to reduce
                nitrogen oxide emissions from internal combustion engines, but a quality EGR system properly fitted can
                also increase engine efficiency. EGR is a required feature on most modern internal combustion engines.
                EGR works by recirculating a portion of an engine’s exhaust stream back in to the engine, optimising the
                incoming flow of oxygen and providing inert gasses that absorb some of the heat generated by the
                combustion process. Because EGR is now a legal requirement, faulty EGR systems will need to be replaced
                as soon as possible. In most modern vehicles, a damaged EGR will trigger a warning light on the
                dashboard and can cause the vehicle to fail an emissions test if checked.</p>
            </div>
          </div>
          <v-expansion-panels popout>
            <v-expansion-panel  class="icon">
              <v-expansion-panel-header class="card-header">
                EGR Valve Problems
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                This clogged EGR valve causes the engine to run badly due to an imbalance in the fuel/air mixture. If
                the jammed EGR valve is not repaired or replaced quickly, all sorts of problems may occur. Four of the
                most common are rough running, high fuel consumption, turbocharger failure and, sometimes, total engine
                failure.
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                Can a bad EGR valve cause a car to stall?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                When the EGR valve is clogged or dirty, as they are prone to, it may not function properly causing the
                engine idle rough, stall at idle speeds, cause the car to get poor fuel mileage, or emit a strong smell
                of fuel due to excess hydrocarbons which also results in failing emissions tests.
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                Is the EGR valve important?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                The EGR valve is an important component in the exhaust gas recirculation process as it helps to prevent
                exhaust valves from overheating, which can accelerate their wear and tear. The EGR valve therefore helps
                maintain the exhaust system at full capacity and increases the longevity of the internal combustion
                process.
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                Does a faulty EGR valve affect performance?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify">One of the first symptoms of a problem with the EGR valve is engine
                  performance issues. A clogged or malfunctioning EGR valve can disrupt the vehicle's air-fuel ratio,
                  which can cause engine performance issues such as a reduction in power, acceleration, and even fuel
                  efficiency.</p>
                <ul class="list mt-2 mb-2">
                  <li>What are the symptoms of a faulty EGR valve on a diesel?</li>
                  <li>Your engine has a rough idle.</li>
                  <li>Your car has poor performance.</li>
                  <li>You have increased fuel consumption.</li>
                  <li>Your car frequently stalls when idling.</li>
                  <li>You can smell fuel.</li>
                  <li>Your engine management light stays on.</li>
                  <li>Reduced Horsepower.</li>
                  <li>Black Smoke or Flames Exiting the Exhaust.</li>
                  <li>Service Engine Light.</li>
                </ul>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                ERG Valve Repair Prices/What is an ERG Valve?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                ERG stands for Exhaust Gas Recirculation and it is a function performed within the combustion engine of
                a car. The measure is sophisticated in the way it is carried out as exhaust gasses are recirculated back
                into the inlet manifold to be used for combustion again. The reason that EGR takes place is to reduce
                the production of oxides of nitrogen which is harmful to breathe in and is damaging to the environment.
                The impact of exhaust gas being recirculated is a drop-in engine performance and fuel economy. Diesel
                cars are also subject to an increase in the production of soot and harmful particulates. However, new
                engines are able to utilise a variety of clever electronic control strategies to reduce the impact of
                using an EGR system. At the heart of the ERG system is the ERG valve, a part which has evolved over time
                to be more efficient and effective. For example, the part used to be pneumatically operated which
                limited it to only an 'open' or 'close' setting, however, the ECU is used to allow continuous levels of
                adjustability in new models. An ERG valve has to be highly robust as exhaust fumes travel through at
                extremely high temperatures and velocity. There is also a high volume of soot and particulate matter
                carried by the fumes and as it has not passed through the DPF, it can build-up in the ERG system,
                causing problems.
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel  class="icon">
              <v-expansion-panel-header class="card-header">
                EGR Valve Problems
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                When there is a build-up of soot and particulate matter, the EGR valve can become stuck open or closed
                as the substance can become tar like. A blocked EGR valve could be the cause of the engine light in your
                car switching on as the engine emissions system will not be performing properly. Wiring and pneumatics
                could be the root cause of ERG problems as the communication between the ERG valve and ECU may be
                compromised. This can be a difficult problem to diagnose as the ERG valve is not the most common cause
                of the engine warning light coming on and mechanics may not decide to look at the part until after
                checking more obvious potential causes. However, using an intelligent diagnostic tool which connects
                directly to the ECU in your car, a mechanic may be able to see the problem immediately. However, the ECU
                will only be able to tell if there is an ERG problem if there is a total failure. It will not be able to
                detect degradation. If the ERG valve is stuck open, your car will suffer from a rough idle and a drop-in
                engine performance as well as a decrease in fuel economy. If the ERG valve is jammed shut, there may be
                an increase in the temperature within the cylinder which may lead to engine knocking. Fortunately,
                modern cars are fitted with knock sensors which will enable the car to adapt accordingly.
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                What does EGR removal do?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                The EGR valve works by recirculating a measured amount of the exhaust gases back into the engine through
                the air intake system, reducing the amount of emissions the engine produces.
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                What controls the EGR valve?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                The fuel air mixture can also spontaneously combust, causing valve clatter and damaging the engine.
                Allowing a small amount of exhaust gas back into the intake reduces combustion chamber temperature.
                Regulating the flow of exhaust gas is the job of the EGR system. What will a stuck EGR valve do? An EGR
                valve that is stuck open: if your truck has a mechanical EGR valve and it happens to be stuck open, it
                will act as a conduit which causes a vacuum leak in the engine. Some of the manifestations of this
                include rough idling and even a feeling of hesitation when you try to accelerate Why does an EGR valve
                fail? This is when the EGR valve mechanism remains shut when the engine is at a high RPM. This causes a
                high temperature in the combustion chamber due to the absent exhaust gas cooling effects, the production
                of the nitrogen compounds will further lead into more detonation which is burning the fuel without any
                ignition. Can a faulty EGR valve cause bad starting? An increase in hydrocarbon emissions isn't
                necessarily caused by a stuck-open EGR valve. Problems in other systems may cause this same symptom as
                well: a leaking fuel injector, bad ignition timing, bad cylinder compression, bad oxygen sensor, or
                other problems
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                Can a faulty EGR valve cause misfire?
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                But the cause might be anything from a hard-to-find vacuum leak to dirty fuel injectors, low fuel
                pressure, a weak ignition coil, bad plug wires, or compression problems. An EGR valve that is leaking
                can also act like a vacuum leak and cause a random misfire Replacing an EGR Valve If your car needs to
                have its EGR valve removed, you will have to pay for a new part and the labour time of the mechanic.
                Fortunately, this is not the most complex of repairs as the part is not usually buried too deeply within
                a car engine. However, the only way to know how much an ERG valve replacement will cost on your specific
                car is by getting a range of quotes from the Many Autos. Finding a mechanic, you can trust to do a good
                job and charge a fair price for EGR Valve, is not always easy which is why we have simplified the
                process off Many Autos car repair Service.
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel >
              <v-expansion-panel-header class="card-header">
                EGR Valve Replacement Free Collection and Delivery
              </v-expansion-panel-header>
              <v-expansion-panel-content eager class="card-header-body">
                <p class="text-teal text-18 justify"> Sometimes, the worst part of getting your car fixed is having to
                  bring it to the garage. We are therefore happy to offer our customers a free collection and delivery
                  service If you prearrange a collection, we will pick your car up from your home or place of work and
                  drive it to our premises, carry out all the necessary work (having consulted you) and deliver it back
                  to you at the end of the day.</p>
                <p class="text-teal text-18 justify">We are able to tow, jump start or repair your vehicle if you are
                  experiencing problems or broken down for a small fee. If we can't sadly start your vehicle, we can
                  contact a local recovery firm to collect your vehicle for a very competitive price.</p>
                <ul class="list mt-2 mb-2">
                  <li>Don't want to waste your day off? </li>
                  <li>You don't have the time to take your car in for a service or repairs? </li>
                  <li>Have you got problems with getting to and from the garage? </li>
                </ul>
                <p class="text-teal text-18 justify">Here at Many Autos, we believe that we offer a valuable product
                  with our Free Collection and Delivery Service, we can collect either from your place of work or from
                  your home address. If you are unsure about whether the address you are considering having your vehicle
                  collected from is not within our range, then please do contact us.<br></p>
                <p class="text-teal text-18 justify">Many Autos operate a fleet of pool cars with a dedicated driver, so
                  wherever we are collecting from, we need to be able to leave one of our pool vehicles either in your
                  work car park / parking space, or if in a residential area, we would need to be able to leave our car
                  either at your house or on the road with a permit if required. We would be grateful if you could bear
                  this in mind when booking to use our free Collection and delivery service</p>

              </v-expansion-panel-content>
            </v-expansion-panel>
          </v-expansion-panels>

        </section>

      </div>
    </div>
  </page-layout>
</template>

<script>
import PageLayout from '@/layouts/page-layout';

const URL = process.env.APP_URL;

export default {
  components: {
    PageLayout
  },

  head: {
    title: 'EGR Valve Replacement | EGR Valve Repair',

    meta: [
      {
        hid: 'description', name: 'description', 
        content: 'Many Autos Provide Quality services of EGR valve, EGR Valve repair Many Autos Aim is to Provide Best car repair Services to Our Customer bring your car at the best car garage in United Kingdom for EGR Valve Replacement.'
      },
      {
        name: 'keywords', 
        content: 'exhaust gas recirculation, egr valve, new egr valve, egr valve repair, egr valve replace, egr valve replacement, Car Garage in United Kingdom, Car Repair Services'
      },
      {
        hid: 'og:title',
        property: "og:title", 
        content: "EGR Valve Replacement | EGR Valve Repair"
      },
      {
        hid: 'og:type',
        property: "og:type", 
        content: "website"
      },
      {
        hid: 'og:url',
        property: "og:url", 
        content: URL
      },
      {
        hid: 'og:image',
        property: "og:image", 
        content: "logo-default.png"
      },
      {
        hid: 'og:site_name',
        property: "og:site_name", 
        content: "ManyAutos LTD"
      },
      {
        hid: 'og:description',  property: 'og:description', 
        content: "Many Autos Provide Quality services of EGR valve, EGR Valve repair Many Autos Aim is to Provide Best car repair Services to Our Customer bring your car at the best car garage in United Kingdom for EGR Valve Replacement."
      },
      {
        name: "twitter:card", 
        content: "summary"
      },
      {
        name: "twitter:title", 
        content: "EGR Valve Replacement | EGR Valve Repair"
      },
      {
        name: "twitter:description", 
        content: "Many Autos Provide Quality services of EGR valve, EGR Valve repair Many Autos Aim is to Provide Best car repair Services to Our Customer bring your car at the best car garage in United Kingdom for EGR Valve Replacement."
      },
      {
        name: "twitter:image", 
        content: "logo-default.png"
      },
      {
        itemprop: "image", 
        content: "logo-default.png"
      },
      {
        hid: 'og:type',
        property: "og:type", 
        content: "business.business"
      },
    ]
  }
}
</script>

<style lang="scss" scoped>
.card-header{
    background: whitesmoke;
    border: 1px solid #ececec;
    color: #1ea5c7;
    padding: 18px;
    font-weight: 400;
    font-size: 16px;
    line-height: normal;
}
.card-header-body{
    background-color: #fff;
    padding-top: 16px;
}
</style>